---
title: "Mentor Call Skills"
editor: 
  markdown: 
    wrap: 72
---

We have five Mentor Calls as a full community. Here we detail the skills
and practices Mentors experienced and experimented with in each Call.

How might you reuse these? Moving from "open science from something I do
alone" to "open science is something I support in others".

## Call 1 Openscapes mindset for mentors

### What does it mean to be a mentor? What does Open Science at NMFS mean?

-   **Speaking up/sharing about yourself for 4 minutes** - a challenge
    for some to take up that space, a challenge for others to limit to
    that space.
-   **Keeping on time** - as a speaker and as a timekeeper
-   **Listening: giving space/silence. Not jumping in** - get
    comfortable with discomfort
-   **Live contributing to collaborative google doc** - hear from more
    voices than we could only out loud, both time-wise and due to power
    structures
-   **Learned emoji shortcut** - not frivolous; a way to connect, side
    conversations and encouragement to build relationships
-   **Saw us adjusting time on the fly in the doc and verbally** - open
    facilitation

### Your tasks before next Call

1.  **Seaside Chat:** Organize 1 hour with mentors at your center/office
    (or other people from other centers/offices), to discuss how you
    could improve workflows with open science in your own work, your own
    center, or more broadly. You could also discuss these readings 
2.  **Readings**: Read [Shifting institutional culture to develop
    climate solutions with Open
    Science](https://eartharxiv.org/repository/view/5948/) (2023
    preprint) and [How coaching skills have made us better open data
    science
    mentors](https://openscapes.org/blog/2023-05-17-mentor-coach/) (May
    2023), both coauthored by NMFS Mentors, (and \<20 mins combined). 
3.  **(optional) Attend** **Coworking**. We'll send a recurring calendar
    invite for the weeks between Mentors Calls, Tuesdays, 12:30 - 1:30
    pm PT. ([find your local
    time](https://www.timeanddate.com/worldclock/fixedtime.html?msg=NMFS+Openscapes+Mentors+Coworking&iso=20231024T1230&p1=1050&ah=1)).
    On Oct 24, Eli Holmes will report on PARR and the new 2022 memo and
    changes to our data workflows that are being proposed, and discuss
    how these changes will impact staff. (Eli is the NMFS Public Access
    of Research Results (PARR) representative on the NOAA PARR working
    group.)

## Call 2 Developing strong open and collaborative Communities

### What skills can we develop to support each other? What are the elements of successful open communities? What NOAA & NMFS open science communities do we like to participate in?

-   **Active listening and asking powerful questions** - coaching to
    empower people to find their own solutions rather than suggesting
    our ideas of what they should do
-   **Vulnerability, yes! Shame, no** - learning and building trust by
    getting curious with each other
-   **Leveraging the experiences of a community** - Kathryn, Ady &
    Christine presenting
-   **You don't have to be an expert to teach** - Christine
    screensharing an efficiency tip she just learned
-   **Sharing open resources for reuse** - slides for 12-minute,
    5-minute, or 1-slide only presentations
-   **Crowdsourcing resources** - a list of NOAA & NMFS communities we
    recommend
-   **Making time for live clarification** - open facilitation 'til we
    all know the plan
-   **Bringing attention to or sharing gratitude for a colleague** -
    coaching kudos and examples of raising people up

### Your tasks before next Call

1.  **Seaside Chat:** Organize 1 hour with mentors at your center/office
    (or other people from other centers/offices), to discuss how you
    could improve workflows with open science in your own work, your own
    center, or more broadly. You could also discuss these readings
    a.  Continue to add to 'seeking mentors for Seaside Chat' in the
        'Fall 2023 Openscapes mentors cohort' sheet
    b.  Share your Seaside Chat report outs in our doc
2.  **Readings**: Read [19 reasons why technologists don't want to work
    at your government
    agency](https://ben.balter.com/2015/04/21/why-technologists-dont-want-to-work-at-your-agency/),
    Ben Balter
3.  **Optional themed seaside chat.** In between the full cohort calls,
    Eli will hold optional Seaside Chats open to any mentors. We'll
    discuss Open Data and Open Science issues affecting NOAA Fisheries.
    Wed, Nov 8, Eli will give a brief update on what is happening at the
    NOAA level re Open Science. We've sent calendar invites.

## Call 3 Experiential learning

### **We converged on open science challenges topics and people who want to work together** and we **learned about and practiced experiential learning.**

-   **Pitching ideas** - to connect with colleagues

-   **Listening** - listening to understand, avoiding solutioneering

-   **Asking powerful questions** - often begin with \"what\", \"what
    else?\", never yes/no

-   **Breaking down activities into teaching concepts** - identifying
    and letting go of extra topics

-   **Do - Reflect - Apply** approach to teaching

-   **Time constraints** - how constraints both for planning time and
    teaching time can help determine scope of an activity

### Your tasks before next Call

1.  **Seaside Chat:** Have and report-out from your small-group Seaside
    Chats, building from topics in the Fall 2023 Openscapes mentors
    sheet

    a.  What help do you need to arrange these?
    b.  Share your meeting time so others can join. Options: post to our
        Google Space, Mentors Calendar, or add to column H in the Fall
        2023 Openscapes mentors sheet.
    c.  Share your Seaside Chat report outs in the
        SeasideChats_ReportOuts \[ nmfs-openscapes-mentors \] doc.

2.  **Open Science News**: Share your Open Science news in the [Open
    Science/Open Data Weekly
    Updates](https://docs.google.com/document/d/1FPei7lBc54VwzZK2qCT9cnrU8-ISZbtQuP2rkg3y3Nc/edit#heading=h.2uk93pxi4pkb)
    doc

3.  **Readings**: [Tips and Tools for Gentle R
    Introductions](https://allisonhorst.github.io/qmss-r-teaching-tools/)
    (slides, by Allison Horst)

4.  **Optional themed seaside chat - Nov 20, 1-2pm PT.** In between the
    full cohort calls, we will hold optional themed Seaside Chats open
    to any mentors. Mon, Nov 20 1-2pm PT, Julie and Eli will give an
    overview of the Openscapes Champions Program, our goals for the
    Feb-Mar 2024 NMFS Champions Cohorts and how this fits into the
    broader plan for NMFS Open Science.
